sudo: true
language: haskell

branches:
  only:
  - master

git:
  depth: 5

ghc:
  - "8.6.5"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

addons:
  ssh_known_hosts:
    - codetalk.io
    - direct.codetalk.io

before_install:
  # Decrypt the encrypted key.
  - openssl aes-256-cbc -K $encrypted_184c99a00c47_key -iv $encrypted_184c99a00c47_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  # Add it to SSH.
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  # Setup stack.
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Install sass/compass.
  - gem install compass

install:
  # Build some of the dependencies separately, so we don't run out of memory.
  - travis_wait stack --system-ghc -j 2 build --fast aeson --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast happy --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast cryptonite --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast cryptohash --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast mtl --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast pandoc --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast blaze-html --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast tagsoup --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast wai --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast warp --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast yaml --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast text --no-terminal --skip-ghc-check
  - travis_wait stack --system-ghc -j 2 build --fast lrucache --no-terminal --skip-ghc-check
  # Build the rest of the dependencies.
  - travis_wait 60 stack --system-ghc -j 2 build --fast --no-terminal --skip-ghc-check --only-dependencies

before_script:
  # Build the site itself.
  - travis_wait stack --system-ghc -j 2 build --fast --no-terminal --skip-ghc-check
  # First clean up and then build the site.
  - travis_wait stack --system-ghc exec -- hakyll-site clean
  - travis_wait stack --system-ghc exec -- hakyll-site build

script:
  # Generate the CSS from the SCSS files.
  - sass resources/scss/app.scss:_site/app.css --style compressed
  # Upload the site via rsync.
  - rsync -rav -e "ssh -l ec2-user" $TRAVIS_BUILD_DIR/_site/* direct.codetalk.io:/usr/share/nginx/codetalk.io
  # Make sure the images have the right permission.
  - ssh ec2-user@direct.codetalk.io "chmod -R +rx /usr/share/nginx/codetalk.io/resources/images"
  # Clear the CloudFlare cache.
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
      -H "X-Auth-Email: ${CF_EMAIL}" \
      -H "X-Auth-Key: ${CF_API_TOKEN}" \
      -H "Content-Type: application/json" \
      --data '{"purge_everything":true}'

notifications:
  slack:
    secure: K2I7egDUwVWAW83gVN46x0J8VIta1zKHI1wne8bz1ziE4a6ILoHSq67s1N5IuSyekHBnbE0OkZ/wqqQWBPKNo75c/kgW487jTCUOxPen2kRfCyHDhH12gDo0+uYzkOqDfRwVQFlXzBXsJ5GafNYfw4Q+YRZY44WbISt1v9OKrt7LsiweNeclSff3RIy59j7D91WqO3GDpXUHgzrewc3YEIYrgEqnm6qefIVTjMxMK4HNuPYetKOJVXHYbs+zd8Xl+7BZSZ7P4BXYZYn6FG2ui0n1xnjRSwDs/75HVRnXg9ivvRV0lpaQwXAyr8gaZvPhaUjYdtvg1ihXNX10C5cWhiqS3OtiN7CpEoKCHDdtV89EToa9HG7XllCT0eP3UIn/WRPv9lsvZz41piutBgUmwwhol/+40++cmxiGwt02xNpC0yo6No0ZRpebRu+ByRvbS2uSg9ZhwXQ2pb//lhN7kvtipimm1Z6H88ExCfnZ4RbPfTA+pvxe/qhgzDeu9NAkaKh5mNcEaiUbT3M/InpggaE5hsFfPW6BlrztNupo0r0tmVMjEXcKMtLn1DUKxKP0f0g/N22Cg963miJzV9mxBbekLt/rQb7pDO5AZty98n4zbaS7vX023CpzJS7CS5T4a8njzYV4sLx8y/7asn6QkQ+2R9bS+Rx0emZAYf0OqZY=
  email:
    on_success: never
    on_failure: always
