language: generic

sudo: false

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack-work-cache
  - .stack-work

branches:
  only:
  - master

before_install:
  # Setup stack.
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Install sass/compass.
  - gem install compass

install:
  # Setup GHC.
  - travis_wait stack -j 2 setup --no-terminal --skip-ghc-check
  - stack exec -- ghc --version
  # Build some of the dependencies separately, so we don't run out of memory.
  - travis_wait stack -j 2 install aeson --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install happy --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install cryptonite --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install cryptohash --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install mtl --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install pandoc --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install blaze-html --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install tagsoup --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install wai --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install warp --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install yaml --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install text --no-terminal --skip-ghc-check
  - travis_wait stack -j 2 install lrucache --no-terminal --skip-ghc-check
  # Build the rest of the dependencies.
  - travis_wait stack -j 2 build --no-terminal --skip-ghc-check --only-dependencies

script:
  # Build the site itself.
  - travis_wait stack -j 2 build --no-terminal
  # First clean up and then build the site.
  - travis_wait stack exec -- hakyll clean
  - travis_wait stack exec -- hakyll build

after_success:
  # Generate the CSS from the SCSS files.
  - sass resources/scss/app.scss:_site/app.css --style compressed
  # Upload the site via rsync.
  - rsync -rav -e "echo '$TRAVIS_CODETALK_IO_SSH_KEY' | ssh -i /dev/stdin _site/* ec2-user@codetalk.io:/usr/share/nginx/codetalk.io" --delete-after
  # Make sure the images have the right permission.
  - echo "$TRAVIS_CODETALK_IO_SSH_KEY" | ssh -i /dev/stdin ec2-user@codetalk.io "chmod -R +rx /usr/share/nginx/codetalk.io/resources/images"
  # Clear the CloudFlare cache.
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
      -H "X-Auth-Email: ${CF_EMAIL}" \
      -H "X-Auth-Key: ${CF_API_TOKEN}" \
      -H "Content-Type: application/json" \
      --data '{"purge_everything":true}'

notifications:
  slack:
    secure: K2I7egDUwVWAW83gVN46x0J8VIta1zKHI1wne8bz1ziE4a6ILoHSq67s1N5IuSyekHBnbE0OkZ/wqqQWBPKNo75c/kgW487jTCUOxPen2kRfCyHDhH12gDo0+uYzkOqDfRwVQFlXzBXsJ5GafNYfw4Q+YRZY44WbISt1v9OKrt7LsiweNeclSff3RIy59j7D91WqO3GDpXUHgzrewc3YEIYrgEqnm6qefIVTjMxMK4HNuPYetKOJVXHYbs+zd8Xl+7BZSZ7P4BXYZYn6FG2ui0n1xnjRSwDs/75HVRnXg9ivvRV0lpaQwXAyr8gaZvPhaUjYdtvg1ihXNX10C5cWhiqS3OtiN7CpEoKCHDdtV89EToa9HG7XllCT0eP3UIn/WRPv9lsvZz41piutBgUmwwhol/+40++cmxiGwt02xNpC0yo6No0ZRpebRu+ByRvbS2uSg9ZhwXQ2pb//lhN7kvtipimm1Z6H88ExCfnZ4RbPfTA+pvxe/qhgzDeu9NAkaKh5mNcEaiUbT3M/InpggaE5hsFfPW6BlrztNupo0r0tmVMjEXcKMtLn1DUKxKP0f0g/N22Cg963miJzV9mxBbekLt/rQb7pDO5AZty98n4zbaS7vX023CpzJS7CS5T4a8njzYV4sLx8y/7asn6QkQ+2R9bS+Rx0emZAYf0OqZY=
  email:
    on_success: never
    on_failure: always
