language: generic

sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

branches:
  only:
    - master

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - gem install compass

install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check build --only-snapshot

script:
  - stack build --no-terminal
  - stack exec -- hakyll build

after_success:
  - ./deploy.sh
