resolver: nightly-2021-02-27

packages:
  - "."

extra-deps:
  - hakyll-shakespeare-0.1.0.0.2
  - hakyll-4.13.4.1
  - pandoc-2.11.3.1
  - pandoc-citeproc-0.17.0.2
  - citeproc-0.3.0.1
  - commonmark-0.1.1.2
  - commonmark-extensions-0.2.0.4
  - commonmark-pandoc-0.2.0.1
  - doctemplates-0.9
  - pandoc-types-1.22
  - skylighting-0.10.2
  - skylighting-core-0.10.2

allow-newer: true

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
