resolver: nightly-2022-07-23 # GHC 9.2.3

packages:
  - "."

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
