resolver: lts-14.27

packages:
- '.'

extra-deps:
- hakyll-shakespeare-0.1.0.0.2
- hakyll-4.13.0.1

allow-newer: true

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
