media:
  input: resources/images
  output: /resources/images

content:
  - name: posts
    label: Posts
    path: posts
    type: collection
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
      fields: [ title, tags, date ]
      primary: title
      sort: [ date, title ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: tags
        label: Tags
        type: string
        description: Comma-separated list of tags
        required: true
      - name: date
        label: Date
        type: date
        options:
          format: YYYY-MM-DD
        required: false
      - name: versions
        label: Versions
        type: string
        description: A list of relevant tool/software versions or commits used in the blog post
        list: true
        required: false
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
        required: true
  - name: drafts
    label: Drafts
    path: drafts
    type: collection
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
      fields: [ title, tags, date ]
      primary: title
      sort: [ date, title ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: tags
        label: Tags
        type: string
        description: Comma-separated list of tags
        required: true
      - name: date
        label: Date
        type: date
        options:
          format: YYYY-MM-DD
        required: false
      - name: versions
        label: Versions
        type: string
        list: true
        description: A list of relevant tool/software versions or commits used in the blog post
        required: false
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
        required: true