resolver: lts-20.9 # GHC 9.2.5

packages:
  - "."

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
