name: haskell-lens
version: 0.1.0.0
github: "codetalkio/codetalk.io"
license: BSD3
author: "Christian Laustsen"
maintainer: "ckl@codetalk.io"
copyright: "Christian Laustsen"
description: Common JSON patterns using Haskell Lens

# Manage your dependencies here.
dependencies:
  - base
  - bytestring
  - aeson
  - deriving-aeson
  - lens
  - generic-lens

executables:
  simple-program-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Wpartial-fields
      - -fhide-source-paths
      - -Wno-type-defaults
