name: "CD: Deploy site"

# Check out https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
on:
  release:
    types: [released]
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - "posts/**"
  #     - "resources/**"
  #     - "src/**"
  #     - "templates/**"
  #     - ".github/workflows/ci-cd.yml"
  #     - "stack.yaml"

concurrency: production

jobs:
  cd:
    runs-on: ubuntu-20.04
    environment:
      name: production
      url: https://codetalk.io
    steps:
      - uses: actions/checkout@v1
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: assets
      #     path: ./_site

      - name: Download latest release
        run: |
          gh release download --pattern "_site" --dir ./_site
          ls _site

      - name: Upload site to S3
        run: |
          aws s3 sync _site s3://codetalk.io --delete
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Purge CloudFront cache
      #   run: |
      #     curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" \
      #       -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" \
      #       -H "Content-Type: application/json" \
      #       --data '{"purge_everything":true}'
      #   env:
      #     CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
