name: cd

# Check out https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
on:
  push:
    paths:
      - 'posts/**'
      - 'resources/**'
      - 'src/**'
      - 'templates/**'
      - '.github/workflows/cd.yml'

jobs:
  cd:
    runs-on: ubuntu-20.04
    env:
      GHC_VERSION: '8.8.3'
      CABAL_VERSION: '3.2'
      STACK_VERSION: '2.5.1.1'
    steps:
      - uses: actions/checkout@v1

      # Setup tooling
      - uses: actions/setup-haskell@v1.1
        name: Setup Haskell Stack
        with:
          ghc-version: ${{env.GHC_VERSION}}
          cabal-version: ${{env.CABAL_VERSION}}
          stack-version: ${{env.STACK_VERSION}}
          enable-stack: true
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install compass for scss
        run: |
          gem install compass

      # Enable cache for cabal
      - uses: actions/cache@v1
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-${{env.GHC_VERSION}}-stack-work
      - uses: actions/cache@v1
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{env.GHC_VERSION}}-cabal-store
      - uses: actions/cache@v1
        name: Cache stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{env.GHC_VERSION}}-stack


      - name: Install dependencies
        run: |
          stack --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build executable
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
          stack exec --system-ghc -- hakyll-site clean
          stack exec --system-ghc -- hakyll-site build


      - name: Upload site to S3 and purge CloudFront cache
        if: github.ref == 'refs/heads/master'
        run: |
          # Optimize the CSS output
          sass resources/scss/app.scss:_site/app.css --style compressed

          # Upload the site to the S3 bucket
          aws s3 sync _site s3://codetalk.io --delete

          # Clear the aggressive CloudFlare cache
          curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" \
            -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
