name: "CI: Upload Binary"

# Check out https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
on:
  push:
    branches:
      - master
      - main
    paths:
      - "src/**"
      - ".github/workflows/ci-binary.yml"
      - "stack.yaml"

jobs:
  ci:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    environment:
      name: ci
    env:
      GHC_VERSION: "8.10.2"
      CABAL_VERSION: "3.4.0.0"
      STACK_VERSION: "2.5.1"
    steps:
      - uses: actions/checkout@v1

      # Setup tooling
      - uses: haskell/actions/setup@v1
        name: Setup Haskell Stack
        with:
          ghc-version: ${{env.GHC_VERSION}}
          cabal-version: ${{env.CABAL_VERSION}}
          stack-version: ${{env.STACK_VERSION}}
          enable-stack: true

      # Enable cache for cabal and stack
      - uses: actions/cache@v2
        name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{env.GHC_VERSION}}-cabal-store-${{ hashFiles('*.cabal') }}
      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{env.GHC_VERSION}}-stack-${{ hashFiles('stack.yaml.lock') }}

      - name: Install dependencies
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build executable
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --local-bin-path ./dist --copy-bins
          ls ./dist

      - uses: codetalkio/release-action@v1
        with:
          artifacts: "./dist/hakyll-site"
          token: ${{ secrets.GITHUB_TOKEN }}
